site_name: Shivam Anand's Site
site_author: Shivam Anand
site_description: >-
  Shivam Anand's Personal Documentation Site
# repo_name: github
# repo_url: https://github.com/anandshivam44/Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.path
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home:
      - About me: index.md
  - Cheat Sheets:
      - aws cli cheat sheet: cheat-sheet-and-snippets/aws-cheat-sheet.md
      - cloudformation cheat sheet: cheat-sheet-and-snippets/cloudformation-cheat-sheet.md
      - docker cheat sheet: cheat-sheet-and-snippets/docker-cheat-sheet.md
      - elastic search cheat sheet: cheat-sheet-and-snippets/elastic-search-cheat-sheet.md
      - gcp gcloud cheat sheet: cheat-sheet-and-snippets/gcloud-cheat-sheet.md
      - git cheat sheet: cheat-sheet-and-snippets/git-cheat-sheet.md
      - helm cheat sheet: cheat-sheet-and-snippets/helm-cheat-sheet.md
      - k8s kubernetes cheat sheet: cheat-sheet-and-snippets/kubectl-cheat-sheet.md
      - linux cheat sheet: cheat-sheet-and-snippets/linux-cheat-sheet.md
      - networking commands cheat sheet: cheat-sheet-and-snippets/networking-cheat-sheet.md
      - regex cheat sheet: cheat-sheet-and-snippets/regex-cheat-sheet.md
      - sql cheat sheet: cheat-sheet-and-snippets/sql-cheat-sheet.md

  - Snippets:
      - Snippets Set 1: Snippets/Snippets1.md
      - One Click Install Apache on Ubuntu: AutomationScriptsSnippets&Files/shell-scripts/install-apache-ubuntu.sh

  - Projects:
      - Encrypt EC2 From CloudFormation: Projects/EncryptEC2FromCloudFormation/EBSEncryption.md
      - Save Cost on EC2 - ShutDown All EC2 at Night: Projects/ShutDownAllEC2EqualIntervalsOfTime/README.md

  - Tutorials:
      - Linux Commands: Tutorials/LinuxCommands.md
      - Setup Ansible: Tutorials/AnsibleAWS.md
      - Generate SSH Key pair & Add to Agent: Tutorials/GenerateKeysAndSSH.md
      - SSH to Docker: Tutorials/SSHToDocker.md
      - Install Kubernetes with KubeAdm: Tutorials/KubernetesWithKubeadm.md
      - EncryptEC2FromCloudFormation: Projects/EncryptEC2FromCloudFormation/EBSEncryption.md
  # - Automation Scripts Snippets & Files:
  #     - aws cli Cheat Sheet: cheat-sheet-and-snippets/AwsCliCheatSheet.md

plugins:
  - search:
      lang: en
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/anandshivam44
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/anandshivam44
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/anandshivam44/
    - icon: fontawesome/solid/paper-plane
      link: mailto:anand.shivam44@yahoo.com

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html

copyright: |
  &copy; 2023 <a href="https://github.com/anandshivam44"  target="_blank" rel="noopener">Shivam Anand</a>
